config/routes.rb
Rails.application.routes.draw do

  root :to => 'welcome#index'

  resources :brackets, except: :destroy
  resources :users, except: :destroy
  resources :groups
  resources :memberships

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get '/stats', to: 'stats#index'
  get '/wcbadmin', to: 'sessions#admin'
  post '/wcblogin', to: 'sessions#newadmin'
  get '/wcbmgmt', to: 'admin#index'
  get '/attempt', to: 'register_attempts#new'
  post '/attempt', to: 'register_attempts#create'
  get '/updateview', to: 'admin#change_view'
  get '/usersearch', to: 'admin#user_search'
  get '/admininfo', to: 'admin#admin_info'
  post '/teamupdate/:id', to: 'admin#team_update', as: 'teamupdate'
  get '/teamindex', to: 'admin#team_index' 
  get '/teamedit/:id', to: 'admin#team_edit', as: 'teamedit'
  get '/rules', to: 'rules#index', as:'rules'
  get '/groupinvite/:id', to: 'groups#invite_others', as: 'inviteothers'
  post '/sendinvite', to: 'groups#send_invite', as: 'sendinvite'
  get '/recoverpassword', to: 'users#recover_password', as: 'recoverpassword'
  post '/recover_password_email', to: 'users#recover_password_email', as: 'recover_password_email'
  get '/password_modify', to: 'users#password_modify', as: 'password_modify'
  get '/registerattempts', to: 'admin#register_attempts'
  get '/howdoesitwork', to: 'welcome#how_does_it_work'
  get '/unsupportedbrowser', to: 'welcome#unsupported_browser'
  get '*path', to: 'welcome#index'
  end

app/models/bracket.rb
class Bracket < ActiveRecord::Base;
	belongs_to :user

	validates :user_id, presence: true
	validates :user_id, uniqueness: true, on: :create 
	validates :a1, :b2, :c1, :d2, :b1, :a2, :d1, :c2, :e1, :f2, :g1, :h2, :f1, :e2, :h1, :g2, :w49, :w50, :w51, :w52, :w53, :w54, :w55, :w56, :w57, :w58, :w59, :w60, :l61, :l62, :w61, :w62, :third, :champion, :presence => true

	before_save :generate_slug
    before_create :zero_scores
    after_save :update_memberships

    def zero_scores
        self.a1s = -1
        self.a2s = -1
        self.b1s = -1
        self.b2s = -1
        self.c1s = -1
        self.c2s = -1
        self.d1s = -1
        self.d2s = -1
        self.e1s = -1
        self.e2s = -1
        self.f1s = -1
        self.f2s = -1
        self.g1s = -1
        self.g2s = -1
        self.h1s = -1
        self.h2s = -1
        self.w49s = -1
        self.w50s = -1
        self.w51s = -1
        self.w52s = -1
        self.w53s = -1
        self.w54s = -1
        self.w55s = -1
        self.w56s = -1
        self.w57s = -1
        self.w58s = -1
        self.w59s = -1
        self.w60s = -1
        self.w61s = -1
        self.w62s = -1
        self.l61s = -1
        self.l62s = -1
        self.thirds = -1
        self.champions = -1
        self.score = 0
    end

	def generate_slug
		bracket_user = User.find(self.user_id)
    	self.slug = bracket_user.first_name.gsub(/['`]/,"").downcase
   	 	self.slug = self.slug.mb_chars.normalize(:kd).gsub(/[^\x00-\x7F]/n,'').to_s
    	self.slug = self.slug.gsub(/\s*@\s*/, "at")
    	self.slug = self.slug.gsub(/\s*&\s*/, "and")
    	self.slug = self.slug.gsub(/\s*[^A-Za-z0-9\.\-]\s*/, '_')
    	self.slug = self.slug.gsub(/_+/,"_")
    	self.slug = self.slug.gsub(/\A[_\.]+|[_\.]+\z/,"")
    	testslug = self.slug
    	slug_match = Bracket.where(slug: testslug).where.not(id: self.id).first
    	i = 2;
    		while (slug_match != nil) do
      		testslug = self.slug + i.to_s
      		slug_match = Bracket.where(slug: testslug).where.not(id: self.id).first
      		i +=1
    		end
    	self.slug = testslug
    end

    def to_param
    	self.slug
    end

    def update_memberships
        this_memberships = Membership.where(user_id: self.user_id)
        if (this_memberships.any?)
            this_memberships.each do |m|
                m.bracket_updated_at = self.updated_at 
                m.save
            end
        end
    end

end

app/controllers/brackets_controller.rb
class BracketsController < ApplicationController
	
  before_action :require_user

  def index

	end
	def new
		@bracket = Bracket.new
    @clear = false
	end
	def create
    	@bracket = Bracket.new(bracket_params)
    	@bracket.user_id = session[:user_id]
      require_same_user(@bracket.user_id)
        if valid_bracket?
      	    if @bracket.save
              update_selections
              flash[:notice] = "Your bracket has been saved."
      	      redirect_to bracket_path(@bracket)    
      	    else
      	      flash.now[:error] = "There was a problem saving the bracket. Please make sure all fields are selected."
      	      render :new
      	    end
        else
          flash.now[:error] = "Your bracket has invalid information. Please make sure all fields are selected correctly."
          render :new
        end
  end

  	def show
  		@allTeams = Team.all
  		if(Bracket.where("user_id = ?",session[:user_id]).blank?)
  			redirect_to new_bracket_path
  		elsif (params.has_key?(:other_bracket) && results_visible?)
          @bracket = Bracket.find_by(slug: params[:id])
          @screen_name = params[:screen_name]
        else
  			 @bracket = Bracket.find_by(user_id: session[:user_id])
      end
  	end

  	def edit
  		if(params.has_key?(:clear))
  			@clear = params[:clear]
  		else
  			@clear = false
  		end
  		if(@clear)
  			@bracket = Bracket.find_by(slug: params[:id])
        @bracket.a1 = @bracket.a2 = @bracket.b1 = @bracket.b2 = @bracket.c1 = @bracket.c2 = @bracket.d1 = @bracket.d2 = nil
  		  @bracket.e1 = @bracket.e2 = @bracket.f1 = @bracket.f2 = @bracket.g1 = @bracket.g2 = @bracket.h1 = @bracket.h2 = nil
        @bracket.w49 = @bracket.w50 = @bracket.w51 = @bracket.w52 = @bracket.w53 = @bracket.w54 = @bracket.w55 = nil
        @bracket.w56 = @bracket.w57 = @bracket.w58 = @bracket.w59 = @bracket.w60 = @bracket.w61 = @bracket.w62 = nil
        @bracket.l61 = @bracket.l62 = @bracket.third = @bracket.champion = nil
      else
			@bracket = Bracket.find(params[:id])
      require_same_user(@bracket.user_id)
		  end
	 end

	def update
    	@bracket = Bracket.find_by(slug: params[:id])
    	@bracket.user_id = session[:user_id]
      require_same_user(@bracket.user_id)
      if valid_bracket?
	       if @bracket.update(bracket_params)
           update_selections
	         redirect_to bracket_path(@bracket.id)    
	       else
	          flash.now[:error] = "There was a problem saving the bracket. Please make sure all fields are selected correctly."
	         render :edit
	       end
      else
      flash.now[:error] = "Your bracket has invalid information. Please make sure all fields are selected correctly."
      render :edit
      end
  end


  	private


    	def bracket_params
        params.require(:bracket).permit!
    	end

    	def bracket_params_update
    	  params.require(:bracket).permit!.except(:user_id)
    	end

      def update_selections
        Team.all.each do |t|
          t.r16_selections = 0
          t.quaterfinals_selections = 0
          t.semifinals_selections = 0 
          t.final_selections = 0 
          t.third_match_selections = 0
          t.champion_selections = 0
          t.third_selections = 0
          t.save
        end
        Bracket.all.each do |b|
          for i in 97..104
              for x in 1..2
                t = Team.find_by(id: b.send(i.chr+x.to_s))
                if(!t.nil?)
                  t.r16_selections +=1
                  t.save
                end
              end
          end
          for i in 49..56
              t = Team.find_by(id: b.send('w'+i.to_s))
              if(!t.nil?)
                t.quaterfinals_selections +=1
                t.save
              end
          end
          for i in 57..60
              t = Team.find_by(id: b.send('w'+i.to_s))
              if(!t.nil?)
                t.semifinals_selections +=1
                t.save
              end
          end
          for i in 61..62
              t = Team.find_by(id: b.send('w'+i.to_s))
              if(!t.nil?)
                t.final_selections +=1
                t.save
              end
          end
          for i in 61..62
              t = Team.find_by(id: b.send('l'+i.to_s))
              if(!t.nil?)
                t.third_match_selections +=1
                t.save
              end
          end
          t = Team.find_by(id: b.third)
            if(!t.nil?)
                t.third_selections +=1
                t.save
            end
          t = Team.find_by(id: b.champion)
            if(!t.nil?)
                t.champion_selections +=1
                t.save
            end
        end
      end

      def valid_bracket?
        valid_bracket = true
        for i in 97..104
          for x in 1..2
            t = Team.find_by(id: params[:bracket][i.chr+x.to_s])
            m = (x % 2) + 1
            if(!t.nil?)
              if(t.send('group') != (i - 32).chr || params[:bracket][i.chr+x.to_s]==params[:bracket][i.chr+m.to_s])
                valid_bracket = false
              end
            else
              valid_bracket = false
            end
          end
        end
        if(valid_bracket)
          if ((params[:bracket][:w49] != params[:bracket][:a1]) && (params[:bracket][:w49] != params[:bracket][:b2])) then valid_bracket = false end
          if ((params[:bracket][:w50] != params[:bracket][:c1]) && (params[:bracket][:w50] != params[:bracket][:d2])) then valid_bracket = false end
          if ((params[:bracket][:w53] != params[:bracket][:e1]) && (params[:bracket][:w53] != params[:bracket][:f2])) then valid_bracket = false end
          if ((params[:bracket][:w54] != params[:bracket][:g1]) && (params[:bracket][:w54] != params[:bracket][:h2])) then valid_bracket = false end
          if ((params[:bracket][:w57] != params[:bracket][:w49]) && (params[:bracket][:w57] != params[:bracket][:w50])) then valid_bracket = false end
          if ((params[:bracket][:w58] != params[:bracket][:w53]) && (params[:bracket][:w58] != params[:bracket][:w54])) then valid_bracket = false end
          if ((params[:bracket][:w51] != params[:bracket][:b1]) && (params[:bracket][:w51] != params[:bracket][:a2])) then valid_bracket = false end
          if ((params[:bracket][:w52] != params[:bracket][:d1]) && (params[:bracket][:w52] != params[:bracket][:c2])) then valid_bracket = false end
          if ((params[:bracket][:w55] != params[:bracket][:f1]) && (params[:bracket][:w55] != params[:bracket][:e2])) then valid_bracket = false end
          if ((params[:bracket][:w56] != params[:bracket][:h1]) && (params[:bracket][:w56] != params[:bracket][:g2])) then valid_bracket = false end
          if ((params[:bracket][:w59] != params[:bracket][:w51]) && (params[:bracket][:w59] != params[:bracket][:w52])) then valid_bracket = false end
          if ((params[:bracket][:w60] != params[:bracket][:w55]) && (params[:bracket][:w60] != params[:bracket][:w56])) then valid_bracket = false end
          if ((params[:bracket][:w61] != params[:bracket][:w57]) && (params[:bracket][:w61] != params[:bracket][:w58])) then valid_bracket = false end
          if ((params[:bracket][:w62] != params[:bracket][:w59]) && (params[:bracket][:w62] != params[:bracket][:w60])) then valid_bracket = false end
          if ((params[:bracket][:l61] != params[:bracket][:w57]) && (params[:bracket][:l61] != params[:bracket][:w58])) then valid_bracket = false end
          if ((params[:bracket][:l62] != params[:bracket][:w59]) && (params[:bracket][:l62] != params[:bracket][:w60])) then valid_bracket = false end
          if ((params[:bracket][:third] != params[:bracket][:l61]) && (params[:bracket][:third] != params[:bracket][:l62])) then valid_bracket = false end
          if ((params[:bracket][:champion] != params[:bracket][:w61]) && (params[:bracket][:champion] != params[:bracket][:w62])) then valid_bracket = false end
          if ((params[:bracket][:l61] == params[:bracket][:w61]) || (params[:bracket][:l61] == params[:bracket][:w62])) then valid_bracket = false end
          if ((params[:bracket][:l62] == params[:bracket][:w61]) || (params[:bracket][:l62] == params[:bracket][:w62])) then valid_bracket = false end
          if (params[:bracket][:champion] == params[:bracket][:third]) then valid_bracket = false end
        end
        return valid_bracket
      end
end

app/views/brackets/_bracket_buttons.html.erb
<div class="navbar">
   	<div class="navbar-inner">
       	<div class="container">	
			<nav class="third-navbar" role="navigation">
				<ul class="nav">
				  <li>
				    <%= link_to 'Go Back', :back %>
				  </li>
				  	<% if !results_visible? %> 
					  	<li>
					  		<%= link_to 'Change Bracket', edit_bracket_path(@bracket.id) if @bracket.user_id == session[:user_id] %>
					  	</li>
					 <% end %>
				</ul>
			</nav>
		</div>
	</div>
</div>

app/views/brackets/_bracket_info.html.erb
<div class="bracket-info">
		<% if @bracket.user_id != session[:user_id] %>
			<h4>You are seeing <%= @screen_name %>'s bracket</h4>
		<% end %> 	
			<h4>Positions Defined: <%= ((positions_defined_teams/34.00) * 100).round(2) %>%   &nbsp&nbsp&nbsp&nbsp   Accuracy: <%= positions_defined_teams > 0 ? ((@bracket.score / (positions_defined_teams * 2.00))*100).round(2) : 0%>%&nbsp&nbsp&nbsp&nbsp Score:&nbsp<%= @bracket.score %>  </h4>
			<% if Time.now < cutover_time %>
				<% if (Time.now + 1.hour) > cutover_time %> 
					<h4 style='color:red'> <%= ((cutover_time - (Time.now + 1.day))/60).round(0) %> minutes left to submit final bracket! </h4>
				<% elsif (Time.now + 1.day) > cutover_time %> 
					<h4 style='color:red'> <%= ((cutover_time - (Time.now + 1.day))/3600).round(0) %> hours left to submit final bracket! </h4>
				<% elsif (Time.now < cutover_time) %> 
					<h4> <%= ((cutover_time - (Time.now + 1.day))/3600/24).round(0) %> days left to submit final bracket! </h4> 
				<% end %>
			<% end %>
			<h4 class='f90'>Symbols: &nbsp&nbsp <span class=<%= get_icon(-1) %> ></span>&nbspNot defined yet&nbsp&nbsp&nbsp&nbsp<span class=<%= get_icon(0) %> ></span>&nbsp0 Points&nbsp&nbsp&nbsp&nbsp<span class=<%= get_icon(1) %> ></span>&nbsp1 Point&nbsp&nbsp&nbsp&nbsp<span class=<%= get_icon(2) %> ></span>&nbsp2 Points</h4>
</div>

app/views/brackets/_edit_bracket_buttons.html.erb
<div class="navbar">
   	<div class="navbar-inner">
       	<div class="container">	
			<nav class="third-navbar" role="navigation">
				<ul class="nav">
				  <li>
				    <%= link_to 'Go Back', :back %>
				  </li>
				  <li>
				  		<%= link_to 'Change Bracket', edit_bracket_path(@bracket.id) if @bracket.user_id == session[:user_id] %>
				  </li>
				  <li>
				  </li>
				</ul>
			</nav>
		</div>
	</div>
</div>

app/views/brackets/edit.html.erb
<%= render 'form' %>
<script>
	$(document).ready(function(){

		$('#bracket-main').hide();
		$('#bracket-loading').show();
		//hide all teams in select opionts
		hideTeams();


		//fix selects with old selections if page reload
		fixSelects();
		$('#bracket-loading').hide();
		$('#bracket-main').show(); 
		
	});
</script>

app/views/brackets/index.html.erb
<h4>Welcome to the World Cup Bracket</h4>

app/views/brackets/new.html.erb
<%= render 'form' %>
<script>
	$(document).ready(function(){

		//hide all teams in select opionts
		hideTeams();


		//fix selects with old selections if page reload
		fixSelects(); 
		
	});
</script>

app/views/brackets/show.html.erb
	<%= render 'bracket_buttons' %>
	<%= render 'bracket_info' %>
	<div class='bracketcontainer container'>
		<div class='bracket-column' id="Round16-1">
			<div class="well bracket well-sm bracket-text">
					<p> 1A vs 2B</p>
					<%= image_tag Team.find(@bracket.a1).flag_url, :class => 'icon' %> <%= Team.find(@bracket.a1).name %> <span class=<%= get_icon(@bracket.a1s) %> ></span>
					<br/>vs<br/>
					<span class=<%= get_icon(@bracket.b2s) %>></span> <%= Team.find(@bracket.b2).name %> <%= image_tag Team.find(@bracket.b2).flag_url, :class => 'icon' %>
			</div>	
			<div class="well bracket well-sm bracket-text">
					<p> 1C vs 2D</p>
					<%= image_tag Team.find(@bracket.c1).flag_url, :class => 'icon' %> <%= Team.find(@bracket.c1).name %> <span class=<%= get_icon(@bracket.c1s) %> ></span>
				<br/>vs<br/>
					<span class=<%= get_icon(@bracket.d2s) %> ></span> <%= Team.find(@bracket.d2).name %> <%= image_tag Team.find(@bracket.d2).flag_url, :class => 'icon' %>
			</div>	
			<div class="well bracket well-sm bracket-text">
					<p> 1E vs 2F</p>
					<%= image_tag Team.find(@bracket.e1).flag_url, :class => 'icon' %> <%= Team.find(@bracket.e1).name %> <span class=<%= get_icon(@bracket.e1s) %> ></span>
				<br/>vs<br/>
					<span class=<%= get_icon(@bracket.f2s) %> ></span> <%= Team.find(@bracket.f2).name %> <%= image_tag Team.find(@bracket.f2).flag_url, :class => 'icon' %>
			</div>	
			<div class="well bracket well-sm bracket-text">
					<p> 1G vs 2H</p>
					<%= image_tag Team.find(@bracket.g1).flag_url, :class => 'icon' %> <%= Team.find(@bracket.g1).name %> <span class=<%= get_icon(@bracket.g1s) %> ></span>
				<br/>vs<br/>
					<span class=<%= get_icon(@bracket.h2s) %> ></span> <%= Team.find(@bracket.h2).name %> <%= image_tag Team.find(@bracket.h2).flag_url, :class => 'icon' %>
			</div>	
		</div>
		<div class='bracket-column qf' id="Quater-finals-1">
			<div class="bracket bracket-qf well well-sm bracket-text">
					<p> Quater-final</p>
					<%= image_tag Team.find(@bracket.w49).flag_url, :class => 'icon' %> <%= Team.find(@bracket.w49).name %> <span class=<%= get_icon(@bracket.w49s) %> ></span>
				<br/>vs<br/>
					<span class=<%= get_icon(@bracket.w50s) %> ></span> <%= Team.find(@bracket.w50).name %> <%= image_tag Team.find(@bracket.w50).flag_url, :class => 'icon' %>
			</div>
			<div class="bracket bracket-qf well well-sm bracket-text">
					<p> Quater-final</p>
					<%= image_tag Team.find(@bracket.w53).flag_url, :class => 'icon' %> <%= Team.find(@bracket.w53).name %> <span class=<%= get_icon(@bracket.w53s) %> ></span>
				<br/>vs<br/>
					<span class=<%= get_icon(@bracket.w54s) %> ></span> <%= Team.find(@bracket.w54).name %> <%= image_tag Team.find(@bracket.w54).flag_url, :class => 'icon' %>
			</div>
		</div>
		<div class='bracket-column sf' id="Semi-finals-1">
			<div class="well bracket bracket-sf well-sm bracket-text">
					<p> Semi-final</p>
					<%= image_tag Team.find(@bracket.w57).flag_url, :class => 'icon' %> <%= Team.find(@bracket.w57).name %> <span class=<%= get_icon(@bracket.w57s) %> ></span>
				<br/>vs<br/>
					<span class=<%= get_icon(@bracket.w58s) %> ></span> <%= Team.find(@bracket.w58).name %> <%= image_tag Team.find(@bracket.w58).flag_url, :class => 'icon' %>
			</div>
		</div>
		<div class='bracket-column' id="Finals">
			<div class="well bracket well-sm bracket-text">
				<h4>Champion</h4>
				<%= image_tag Team.find(@bracket.champion).flag_url, :class => 'icon' %>
				<%= Team.find(@bracket.champion).name %> <span class=<%= get_icon(@bracket.champions) %> ></span>
			</div>
			<div class="well bracket well-sm bracket-text">
					<p> Third Place</p>
					<%= image_tag Team.find(@bracket.third).flag_url, :class => 'icon' %> <%= Team.find(@bracket.third).name %> <span class=<%= get_icon(@bracket.thirds) %> ></span>
			</div>
			<div class="well bracket well-sm bracket-text">
					<p>Final</p>
					<%= image_tag Team.find(@bracket.w61).flag_url, :class => 'icon' %> <%= Team.find(@bracket.w61).name %> <span class=<%= get_icon(@bracket.w61s) %> ></span>
				<br/>vs<br/>
					<span class=<%= get_icon(@bracket.w62s) %> ></span> <%= Team.find(@bracket.w62).name %> <%= image_tag Team.find(@bracket.w62).flag_url, :class => 'icon' %>
			</div>
			<div class="well bracket  well-sm bracket-text">
					<p>Third Place</p>
					<%= image_tag Team.find(@bracket.l61).flag_url, :class => 'icon' %> <%= Team.find(@bracket.l61).name %> <span class=<%= get_icon(@bracket.l61s) %> ></span>
				<br/>vs<br/>
					<span class=<%= get_icon(@bracket.l62s) %> ></span> <%= Team.find(@bracket.l62).name %> <%= image_tag Team.find(@bracket.l62).flag_url, :class => 'icon' %>
			</div>
		</div>
		<div class='bracket-column sf' id="Semi-finals-2">
			<div class="well bracket bracket-sf well-sm bracket-text">
					<p> Semi-final</p>
					<%= image_tag Team.find(@bracket.w59).flag_url, :class => 'icon' %> <%= Team.find(@bracket.w59).name %> <span class=<%= get_icon(@bracket.w59s) %> ></span>
				<br/>vs<br/>
					<span class=<%= get_icon(@bracket.w60s) %> ></span> <%= Team.find(@bracket.w60).name %> <%= image_tag Team.find(@bracket.w60).flag_url, :class => 'icon' %>
			</div>
		</div>
		<div class='bracket-column qf' id="Quater-finals-2">
			<div class="bracket bracket-qf well well-sm bracket-text">
					<p> Quater-final</p>
					<%= image_tag Team.find(@bracket.w51).flag_url, :class => 'icon' %> <%= Team.find(@bracket.w51).name %> <span class=<%= get_icon(@bracket.w51s) %> ></span>
				<br/>vs<br/>
					<span class=<%= get_icon(@bracket.w52s) %> ></span> <%= Team.find(@bracket.w52).name %> <%= image_tag Team.find(@bracket.w52).flag_url, :class => 'icon' %>
			</div>
			<div class="bracket bracket-qf well well-sm bracket-text">
					<p> Quater-final</p>
					<%= image_tag Team.find(@bracket.w55).flag_url, :class => 'icon' %> <%= Team.find(@bracket.w55).name %> <span class=<%= get_icon(@bracket.w55s) %> ></span>
				<br/>vs<br/>
					<span class=<%= get_icon(@bracket.w56s) %> ></span> <%= Team.find(@bracket.w56).name %> <%= image_tag Team.find(@bracket.w56).flag_url, :class => 'icon' %>
			</div>
		</div>
		<div class='bracket-column' id="Round16-2">
			<div class="well bracket well-sm bracket-text">
					<p> 1B vs 2A</p>
					<%= image_tag Team.find(@bracket.b1).flag_url, :class => 'icon' %> <%= Team.find(@bracket.b1).name %> <span class=<%= get_icon(@bracket.b1s) %> ></span>
				<br/>vs<br/>
					<span class=<%= get_icon(@bracket.a2s) %> ></span> <%= Team.find(@bracket.a2).name %> <%= image_tag Team.find(@bracket.a2).flag_url, :class => 'icon' %>
			</div>	
			<div class="well bracket well-sm bracket-text">
					<p> 1D vs 2C</p>
					<%= image_tag Team.find(@bracket.d1).flag_url, :class => 'icon' %> <%= Team.find(@bracket.d1).name %> <span class=<%= get_icon(@bracket.d1s) %> ></span>
				<br/>vs<br/>
					<span class=<%= get_icon(@bracket.c2s) %> ></span> <%= Team.find(@bracket.c2).name %> <%= image_tag Team.find(@bracket.c2).flag_url, :class => 'icon' %>
			</div>	
			<div class="well bracket well-sm bracket-text">
					<p> 1F vs 2E</p><br/>
					<%= image_tag Team.find(@bracket.f1).flag_url, :class => 'icon' %> <%= Team.find(@bracket.f1).name %> <span class=<%= get_icon(@bracket.f1s) %> ></span>
				<br/>vs<br/>
					<span class=<%= get_icon(@bracket.e2s) %> ></span> <%= Team.find(@bracket.e2).name %> <%= image_tag Team.find(@bracket.e2).flag_url, :class => 'icon' %>
			</div>	
			<div class="well bracket well-sm bracket-text">
					<p> 1H vs 2G</p><br/>
					<%= image_tag Team.find(@bracket.h1).flag_url, :class => 'icon' %> <%= Team.find(@bracket.h1).name %> <span class=<%= get_icon(@bracket.h1s) %> ></span>
				<br/>vs<br/>
					<span class=<%= get_icon(@bracket.g2s) %> ></span> <%= Team.find(@bracket.g2).name %> <%= image_tag Team.find(@bracket.g2).flag_url, :class => 'icon' %>
			</div>	
		</div>
	</div>