config/routes.rb
Rails.application.routes.draw do

  root :to => 'welcome#index'

  resources :brackets, except: :destroy
  resources :users, except: :destroy
  resources :groups
  resources :memberships

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get '/stats', to: 'stats#index'
  get '/wcbadmin', to: 'sessions#admin'
  post '/wcblogin', to: 'sessions#newadmin'
  get '/wcbmgmt', to: 'admin#index'
  get '/attempt', to: 'register_attempts#new'
  post '/attempt', to: 'register_attempts#create'
  get '/updateview', to: 'admin#change_view'
  get '/usersearch', to: 'admin#user_search'
  get '/admininfo', to: 'admin#admin_info'
  post '/teamupdate/:id', to: 'admin#team_update', as: 'teamupdate'
  get '/teamindex', to: 'admin#team_index' 
  get '/teamedit/:id', to: 'admin#team_edit', as: 'teamedit'
  get '/rules', to: 'rules#index', as:'rules'
  get '/groupinvite/:id', to: 'groups#invite_others', as: 'inviteothers'
  post '/sendinvite', to: 'groups#send_invite', as: 'sendinvite'
  get '/recoverpassword', to: 'users#recover_password', as: 'recoverpassword'
  post '/recover_password_email', to: 'users#recover_password_email', as: 'recover_password_email'
  get '/password_modify', to: 'users#password_modify', as: 'password_modify'
  get '/registerattempts', to: 'admin#register_attempts'
  get '/howdoesitwork', to: 'welcome#how_does_it_work'
  get '/unsupportedbrowser', to: 'welcome#unsupported_browser'
  get '*path', to: 'welcome#index'
  end

app/views/admin/admin_info.html.erb
<div class="dialog" style="margin-top:50px">
	<h5> Total Number of Resiter Attempts: <%= RegisterAttempt.all.count %></h5>	
	<h5> Total Number of Users Registered: <%= User.all.count %></h5>
	<h5> Total Number of Brackets Created: <%= Bracket.all.count %> </h5>
	<h5> Total Number of Private Groups: <%= Group.where(isprivate: true).count %></h5>
	<h5> Total Number of Public Groups: <%= Group.where(isprivate: false).count %></h5>
</div>

app/views/admin/index.html.erb
<h3>Welcome to Admin Page</h3>

app/views/admin/register_attempts.html.erb
<div class="display-container">
	<table class="table table-striped overflow-400">
			<tr>
				<th>Id</th>
				<th>Email</th>
				<th>Passcode</th>
				<th>Created At</th>
			</tr>
		<% @attempts.all.each do |attempt| %>
				<tr>
					<td><%=  attempt.id %> </td>
					<td><%= attempt.email %> </td>
					<td><%= attempt.passcode %></td>
					<td><%= attempt.created_at %>
				</tr>
		<% end %>
	</table>
</div>

app/views/admin/team_edit.html.erb
	<div class="dialog" style="margin-top:50px">	
		<h4><%= @team.name %></h4>
		<%= form_for @team, :url => teamupdate_path(@team), :method => 'POST' do |f| %>
			<%= render 'shared/display_errors', obj: @team %> 
			<div class='control-group form-row'>
				<%= f.label :r16_defined, class: 'f90' %>
				<%= f.check_box :r16_defined %>
				<%= f.label :r16_madeit, class: 'f90' %>
				<%= f.check_box :r16_madeit %>
				<%= f.label :r16_position, class: 'form-label f90' %>
				<%= f.text_field :r16_position, class: 'form-input', id:'r16_position' %>
			</div>
			<div class='control-group form-row'>
				<%= f.label :quaterfinals_defined, class: 'f90' %>
				<%= f.check_box :quaterfinals_defined %>
				<%= f.label :quaterfinals_madeit, class: 'f90' %>
				<%= f.check_box :quaterfinals_madeit %>
			</div>
			<div class='control-group form-row'>
				<%= f.label :semifinals_defined, class: 'f90' %>
				<%= f.check_box :semifinals_defined %>
				<%= f.label :semifinals_madeit, class: 'f90' %>
				<%= f.check_box :semifinals_madeit %>
			</div>
			<div class='control-group form-row'>
				<%= f.label :final_defined, class: 'f90' %>
				<%= f.check_box :final_defined %>
				<%= f.label :final_madeit, class: 'f90' %>
				<%= f.check_box :final_madeit %>
				<br>
				<%= f.label :third_match_defined, class: 'f90' %>
				<%= f.check_box :third_match_defined %>
				<%= f.label :third_match_madeit, class: 'f90' %>
				<%= f.check_box :third_match_madeit %>
				<br>
				<%= f.label :third_place_defined, class: 'f90' %>
				<%= f.check_box :third_place_defined %>
				<%= f.label :third_place_madeit, class: 'f90' %>
				<%= f.check_box :third_place_madeit %>
				<br>
				<%= f.label :champion_defined, class: 'f90' %>
				<%= f.check_box :champion_defined %>
				<%= f.label :champion_madeit, class: 'f90' %>
				<%= f.check_box :champion_madeit %>
			</div>
			<%= f.submit "Update Team", class: 'btn-wcb-normal form-btn register-button', id: 'signup-button' %>
	<% end %>
	</div>

app/views/admin/team_index.html.erb
<div class="display-container">
	<table class="table"> 
		<tr>
		<td>Team Name</td>
		<td>Made R16</td>
		<td>Made Quaterfinals</td>
		<td>Made Semifinals</td>
		<td>Made Final</td>
		<td>Made 3rd Place Match </td>
		<td>3rd Place</td>
		<td>Champion</td>
	</tr>
	<% Team.all.each do |t| %> 
		<tr>
		<td><%= link_to t.name, teamedit_path(t) %></td>
		<% if t.r16_defined %>
			<% if t.r16_madeit %>
				<td><%= t.r16_position %></td>
			<% else %> 
				<td>No</td>
			<% end %> 
		<% else %> 
			<td>TBD</td>
		<% end %>
		<% if t.quaterfinals_defined %>
			<% if t.quaterfinals_madeit %>
				<td>Yes</td>
			<% else %> 
				<td>No</td>
			<% end %> 
		<% else %> 
			<td>TBD</td>
		<% end %>
		<% if t.semifinals_defined %>
			<% if t.semifinals_madeit %>
				<td>Yes</td>
			<% else %> 
				<td> No </td>
			<% end %>
		<% else %>
			<td>TBD</td>
		<% end %>
		<% if t.final_defined %> 
			<% if t.final_madeit %>
				<td>Yes</td>
			<% else %> 
				<td> No </td>
			<% end %> 
		<% else %>
			<td>TBD</td>
		<% end %>
		<% if t.third_match_defined %>
			<% if t.third_match_madeit %>
				<td>Yes</td>
			<% else %> 
				<td> No </td>
			<% end %>
		<% else %> 
			<td>TBD</td>
		<% end %> 
		<% if t.third_place_defined %> 
			<% if t.third_place_madeit %>
				<td>Yes</td>
			<% else %> 
				<td> No </td>
			<% end %>
		<% else %> 
			<td>TBD</td>
		<% end %>
		<% if t.champion_defined %>
			<% if t.champion_madeit %>
				<td>Yes</td>
			<% else %> 
				<td> No </td>
			<% end %>
		<% else %> 
			<td> TBD </td>
		<% end %>
		</tr>
	<% end %>
	</table>
</div>

app/views/admin/user_search.html.erb
<div class="display-container">
	<table class="table table-striped overflow-400">
			<tr>
				<th>Id</th>
				<th>Email</th>
				<th>First Name</th>
				<th>Last Name</th>
				<th>Has Bracket</th>
				<th>Created At</th>
			</tr>
		<% @users.all.each do |user| %>
				<tr>
					<td><%=  user.id %> </td>
					<td><%= user.email %> </td>
					<td><%= user.first_name %></td>
					<td><%= user.last_name %></td>
					<td><%= Bracket.find_by(user_id: user.id).nil? ? 'No' : 'Yes'%></td>
					<td><%= user.created_at %>
				</tr>
		<% end %>
	</table>
</div>