config/routes.rb
Rails.application.routes.draw do

  root :to => 'welcome#index'

  resources :brackets, except: :destroy
  resources :users, except: :destroy
  resources :groups
  resources :memberships

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get '/stats', to: 'stats#index'
  get '/wcbadmin', to: 'sessions#admin'
  post '/wcblogin', to: 'sessions#newadmin'
  get '/wcbmgmt', to: 'admin#index'
  get '/attempt', to: 'register_attempts#new'
  post '/attempt', to: 'register_attempts#create'
  get '/updateview', to: 'admin#change_view'
  get '/usersearch', to: 'admin#user_search'
  get '/admininfo', to: 'admin#admin_info'
  post '/teamupdate/:id', to: 'admin#team_update', as: 'teamupdate'
  get '/teamindex', to: 'admin#team_index' 
  get '/teamedit/:id', to: 'admin#team_edit', as: 'teamedit'
  get '/rules', to: 'rules#index', as:'rules'
  get '/groupinvite/:id', to: 'groups#invite_others', as: 'inviteothers'
  post '/sendinvite', to: 'groups#send_invite', as: 'sendinvite'
  get '/recoverpassword', to: 'users#recover_password', as: 'recoverpassword'
  post '/recover_password_email', to: 'users#recover_password_email', as: 'recover_password_email'
  get '/password_modify', to: 'users#password_modify', as: 'password_modify'
  get '/registerattempts', to: 'admin#register_attempts'
  get '/howdoesitwork', to: 'welcome#how_does_it_work'
  get '/unsupportedbrowser', to: 'welcome#unsupported_browser'
  get '*path', to: 'welcome#index'
  end

app/models/group.rb
class Group < ActiveRecord::Base;
	has_many :memberships
	has_many :users, through: :memberships
	before_save  :generate_slug

	validates :group_name, presence: true
	validates :passcode, presence: true, on: :create, length: {minimum: 6}
	validates :organizer, presence: true

	def generate_slug
    self.slug = self.group_name.gsub(/['`]/,"").downcase
    self.slug = self.slug.mb_chars.normalize(:kd).gsub(/[^\x00-\x7F]/n,'').to_s
    self.slug = self.slug.gsub(/\s*@\s*/, "at")
    self.slug = self.slug.gsub(/\s*&\s*/, "and")
    self.slug = self.slug.gsub(/\s*[^A-Za-z0-9\.\-]\s*/, '_')
    self.slug = self.slug.gsub(/_+/,"_")
    self.slug = self.slug.gsub(/\A[_\.]+|[_\.]+\z/,"")
    testslug = self.slug
    slug_match = Group.where(slug: testslug).where.not(id: self.id).first
    i = 2;
    	while (slug_match != nil) do
      	testslug = self.slug + i.to_s
      	slug_match = Group.where(slug: testslug).where.not(id: self.id).first
      	i +=1
    	end
    self.slug = testslug
    end

    def to_param
    	self.slug
    end

    def is_member?(user)
        Membership.where(user_id: user, group_id: self.id).exists?
    end

    def is_private?
        self.isprivate 
    end

    def is_organizer?(user)
        self.organizer == user.id
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

	def index
		Membership.uncached do
			@association = Membership.select(:group_id).where(user_id: session[:user_id])
		end
		if(params.has_key?(:page))
			page_index = params[:page]
		else
			page_index = 0
		end
		if(params.has_key?(:sortby))
			page_sortby = params[:sortby]
		else
			page_sortby = 'group_name'
		end
		if(params.has_key?(:sortmode))
			page_sortmode = params[:sortmode]
		else
			page_sortmode = 'ASC'
		end
		if(params.has_key?(:showpublic))
			showpublic = params[:showpublic]
		else
			showpublic = false
		end
		if (showpublic)
			@isprivate = false
			@total_public_groups = Group.where(isprivate: false).count
			if(@total_public_groups < items_per_page)
				@pagination = false
				@memberships = Membership.where(user_id: session[:user_id]).select(:group_id)
				@groups = Group.where(isprivate: false).where.not(id: @memberships)
			else 
				@pagination = true
				@groups = Group.where(isprivate: false).order(page_sortby+' '+page_sortmode).limit(items_per_page).offset(page_index * items_per_page)
			end
		else
			@isprivate = true
			Group.uncached do
				@group = Group.find_by(id: Membership.where(user_id: session[:user_id]).select(:group_id).order(last_viewed: :desc).limit(1))
				if !@group.nil? 
					redirect_to group_path(@group)
				else
					@groups = Group.where(id: @association)
				end
			end
		end
	end

	def new
		@join = false
		@group = Group.new
		@join = params[:join]
	end

	def create
			@group = Group.new(group_params)
			@group.organizer = session[:user_id]
			@group.leader = 0
			if(!@group.isprivate)
				@group.passcode = '000000'
			end
		    if @group.save
		        @membership = Membership.new
				@membership.user_id = session[:user_id]
				@membership.group_id = @group.id
				@membership.user_screen_name = params[:screenname]
				if @membership.save
		     		 redirect_to groups_path()
		     	else
		     		@group.destroy
		     		redirect_to new_group_path()
		     	end
		    else
		      render 'new'
		    end
	end

	def edit 
		@group = Group.find_by(slug: params[:id])
	end

	def update
		@group = Group.find_by(slug: params[:id])
		if @group.update(group_params)
			redirect_to group_path(@group)
		else
			flash[:error] = "There was a problem updating the group"
			redirect_to group_path(slug: params[:id])
		end
	end

	def invite_others
		@group = Group.find_by(slug: params[:id])
	end

	def send_invite
		@group = Group.find_by(slug: params[:id])
		@user = current_user
		recipients = params[:emails].split(/\s*[,;]\s*|\s{1,}/)
  		email_error = false
  		email_errors = []
  		recipients.each do |recipient|
  			if valid_email?(recipient)
				UserMailer.send_join_group_email(@group, recipient, @user).deliver
			else
				email_error = true
				email_errors << recipient
			end
			if(email_error)
				flash[:error] = "There were some errors sending the invitation emails. Make sure you have valid email addresses."
			else
				flash[:notice] = "Invitations sent successfully."
			end		
		end
		redirect_to inviteothers_path(@group)
	end

	def show
		@group = Group.find_by(slug: params[:id])
		if(!@group.nil?)
			membership = Membership.find_by(group_id: @group.id, user_id: session[:user_id])
			if(!membership.nil?)
				membership.last_viewed = Time.now
				membership.save
			end
		else
			redirect_to groups_path()
		end
	end

	def destroy
		@group = Group.find_by(slug: params[:id])
		@memberships = Membership.where(group_id: params[:id])
		if @group.organizer == current_user.id
			if @memberships.destroy_all
				@group.destroy
				redirect_to groups_path()
			else
				flash[:error] = "Error while deleting group."
				redirect_to :back
			end
		end
	end


	private

	def group_params
		params.require(:group).permit(:group_name, :passcode, :isprivate)
	end

	def membership_params
		params.require(:membership).permit(:user_id, :group_id, :user_screen_name)
	end

end

app/views/groups/_group_buttons.html.erb
<div class="navbar">
   	<div class="navbar-inner">
       	<div class="container">	
			<nav class="third-navbar" role="navigation">
				<ul class="nav">
				  `<li>
				    <%= link_to "Go Back", :back %>
				  </li>
				  <li>
				    <%= link_to "Create New Group", new_group_path() %>
				  </li>
				  <li>
				    <%= link_to "Join Public Group", groups_path(showpublic: true) %>
				  </li>
				  <li>
				  		<%= link_to "Join Private Group", new_membership_path(isprivate: true) %>
				  </li>
				</ul>
			</nav>
		</div>
	</div>
</div>

app/views/groups/_group_join.html.erb
	<div class="dialog">
	<%= form_for @group do |f| %>	
		<div class='control-group form-row'>
			<%= f.label :group_name, class: 'form-label col-lg-2 col-lg-offset-1 col-md-3 col-md-offset-1 col-sm-4 col-xs-12' %>
			<%= f.text_field :group_name, class: 'form-input col-lg-3 col-md-4 col-sm-5 col-xs-10' %>
		</div>
		<div class='control-group form-row'>
			<%= f.label :passcode, class: 'form-label col-lg-2 col-lg-offset-1 col-md-3 col-md-offset-1 col-sm-4 col-xs-12' %> 
			<%= f.text_field :passcode, class: 'form-input col-lg-3 col-md-4 col-sm-5 col-xs-10' %>
		</div>
		<div class='control-group form-row'>
			<label for="screen_name" class= 'form-label col-lg-2 col-lg-offset-1 col-md-3 col-md-offset-1 col-sm-4 col-xs-12'>Your screen name for this group</label>
			<input type="text" name="screenname" id="screen_name" class='form-input col-lg-3 col-md-4 col-sm-5 col-xs-10'>
		</div>
		<div class='control-group form-row'>
		<%= f.submit "Create Group", class: 'btn btn-wcb-normal form-btn col-md-offset-4' %>
		</div>
	<% end %>
</div>

app/views/groups/_group_new.html.erb
	<div class="dialog">
	<%= form_for @group do |f| %>	
		<div class='control-group form-row'>
			<%= f.label :group_name, class: 'form-label' %>
			<%= f.text_field :group_name, class: 'form-input', title: 'Enter the name of the group' %>
		</div>
		<br>
		<div class='control-group form-row'>
			<%= f.check_box :isprivate, title: 'Define if the group will be private or public', class: 'form-checkbox'%>
			<label class=''>Private</label> 
		</div>
		<br>
		<div id="div_passcode" class='control-group form-row'>
			<%= f.label :passcode, class: 'form-label' %> 
			<%= f.text_field :passcode, class: 'form-input', title: 'Enter a passcode if group will be private' %>
		</div>
		<div class='control-group form-row'>
			<%= f.check_box :others_can_invite, title: 'Define if ohter members can send invitations for this group', class: 'form-checkbox'%>
			<label>Group Members can send invitations?</label> 
		</div>
		<% if @group.new_record? %>
			<div class='control-group form-row'>
				<label for="screen_name" class= 'form-label'>Your screen name</label>
				<input type="text" name="screenname" id="screen_name" value=<%=current_user.screenname%> class='form-input', title="Define the Screen Name that you will use for this group">
			</div>
		<% end %>
		<div class='control-group form-row center'>
		<%= f.submit @group.new_record? ? "Create Group" : "Update Group", class: 'btn-wcb-normal form-btn' %>
		</div>
	<% end %>
</div>

app/views/groups/_group_show.html.erb
<%= render 'group_view_buttons' %>
	<br>
<div class='reportcontainer' >
	<div class="group-info">
		<div class="span4 col-md-4">
			<p>Select Group: 
			<%= collection_select(:group, :slug, Group.where(id: Membership.where(user_id: current_user.id).select(:group_id)), :slug,  :group_name, {}, {class: 'group-select'}) %> </p>
		</div>
		<div class="span4 col-md-4">
			<p> Group Name: <%= @group.group_name %></p>
			<p> Group Id: <%= @group.id %></p>
			<% if @group.is_private? %>
				<% if @group.others_can_invite || (@group.organizer == current_user.id)%>
					<p> Group Passcode: <%= @group.passcode %></p>
				<% else %> 
				<p> Private Group </p>
				<% end %>
			<% else %>
				<p> Public Group </p>
			<% end %>
		</div>
		<div class="span4 col-md-4">
			<p> Group Organizer: <% if @group.is_organizer?(current_user) %>
			 		You
			 		<% else %>
			 		<%= User.find(@group.organizer).first_name%>  <%=User.find(@group.organizer).last_name %> 
			 		<% end %>
			</p>
			<p> Number of Members: <%= Membership.where(group_id: @group.id).count() %> </p>
			<% if !@group.leader.nil? %>
						<p> Current Leader: <%= User.exists?(@group.leader) ? User.find(@group.leader).first_name+' '+User.find(@group.leader).last_name : "None" %></p> 
			<% end %>
		</div>
	</div>

		<div class="col-md-12 group-table">
			<% @members = Membership.where(group_id: @group.id).order(score: :desc, full_total: :desc, champion: :desc, full_final: :desc, third: :desc, full_third: :desc, bracket_updated_at: :asc) %>
			<% if !@members.empty? %>
				<table class="table table-striped">
					<tr> 
						<td> Rank </td>
						<td> Screen Name </td>
						<td> Score </td>
						<td> Accuracy </td>
						<td> Round of 16 <br> 2 pts / 1 pt</td>
						<td> Quater-finals </td>
						<td> Semi-finals </td>
						<td> Total Correct </td>
					</tr>
					<% rank = 1 %>
					<% @members.each do |member| %>
						<% @bracket = Bracket.find_by(user_id: member.user_id) %>
						<tr>
							<td><%= rank %></td>
							<td> <%= member.user_screen_name %> 
								<% if member.user_id == current_user.id %> 
								  <%= link_to " (change)", 'javascript:void(0)', id: "change-screenname" %>
								<% elsif results_visible? %>
									<% if !@bracket.nil? %> 
										<%= link_to " View Bracket", bracket_path(@bracket, other_bracket: true, screen_name: member.user_screen_name ) %>
									<% else %>
								 		(No bracket created)
									<% end %> 
								<% end %>
								</td>
							<td> <%= member.score %></td>
							<td> <%= @bracket.nil? || positions_defined_teams == 0 ? '0' : ((member.score / (positions_defined_teams*2.00))*100).round(0) %>% </td>
							<td> <%=  ((member.full_r16 / 16.00)*100).round(2) %>% / <%= ((member.half_r16 / 16.00)*100).round(2) %>% </td>
							<td> <%= ((member.full_quaterfinals / 8.00)*100).round(2) %>% </td>
							<td> <%= ((member.full_semifinals / 4.00)*100).round(2) %>% </td>
							<td> <%= ((member.full_total / 34.00)*100).round(2) %>% </td>
						</tr>
						<% rank = rank + 1 %>
					<% end %>
				</table>
			<% end %>
		</div>
</div>
		

<div id="leave-group-message" class="warning-message off">
	<br>
	<h4 class="center">Are you sure you want to leave this group?</h4>
	<br>
	<br>
	<%= link_to "Yes", membership_path(@group), method: 'delete', class: 'btn btn-danger btn-message' %>
	<button type="button" class="btn btn-success btn-message " onclick="clearMessage('#leave-group-message')">No</button>
</div>
<div id="delete-group-message" class="warning-message off">
	<br>
	<h4 class="center">Are you sure you want to delete this group?</h4>
	<br>
	<br>
	<%= link_to "Yes", group_path(@group), method: 'delete', class: 'btn btn-danger btn-message' %>
	<button type="button" class="btn btn-success btn-message " onclick="clearMessage('#delete-group-message')">No</button>
</div>
<div id="screenname-form-message" class="warning-message off">
	<h4 class="center">Enter screen name for this group:</h4>
	<br/>
	<% @this_member = Membership.find_by(user_id: session[:user_id], group_id: @group.id) %>
	<% if !@this_member.nil? %> 
		<%= form_for @this_member do |f| %>
		<%= f.text_field :user_screen_name, class: '' %>
		<br/>
		<br/>
		<br/>
		<button type="button" class="btn btn-primary col-xs-4 col-xs-offset-1" id="cancel-screenname">Cancel</button>
		<%= f.submit  "Save", class: 'btn btn-success col-xs-4 col-xs-offset-2' %>
		<% end %>
	<% end %>
</div>

<script>
		$('#cancel-screenname').click(function (event) {
			clearMessage("#screenname-form-message");
		});
		$('#change-screenname').click(function (event) {
			showMessage("#screenname-form-message");
		});
		$('#button_leave_group').click(function (event) {
			showMessage("#leave-group-message");
		});	
		$('#group_slug').change(function (event) {
			var newGroup = '/groups/'+ $(this).val();
			location.href = newGroup;
		});	

</script>

app/views/groups/_group_show_public.html.erb
	<%= render 'group_buttons' %>
	<br>
<div class='reportcontainer' >
	<div class="group-info">
		<div class="span4 col-md-4">
			<p>Select Group: 
			<%= collection_select(:group, :slug, Group.where(id: Membership.where(user_id: current_user.id).select(:group_id)), :slug,  :group_name, {}, {class: 'group-select'}) %> </p>
		</div>
		<div class="span4 col-md-4">
			<p> Group Name: <%= @group.group_name %></p>
			<p> Group Id: <%= @group.id %></p>
			<% if @group.is_private? %>
				<% if @group.others_can_invite || (@group.organizer == current_user.id)%>
					<p> Group Passcode: <%= @group.passcode %></p>
				<% else %> 
				<p> Private Group </p>
				<% end %>
			<% else %>
				<p> Public Group </p>
			<% end %>
		</div>
		<div class="span4 col-md-4">
			<p> Group Organizer: <%= User.find(@group.organizer).first_name %> <%= User.find(@group.organizer).last_name %> </p>
			<p> Number of Members: <%= Membership.where(group_id: @group.id).count() %> </p>
			<% if !@group.leader.nil? %>
						<p> Current Leader: <%= User.exists?(@group.leader) ? User.find(@group.leader).first_name+' '+User.find(@group.leader).last_name : "None" %></p> 
			<% end %>
		</div>
	</div>

		<div class="col-md-12 group-table">
			<% @members = Membership.where(group_id: @group.id).order(score: :desc, full_total: :desc, champion: :desc, full_final: :desc, third: :desc, full_third: :desc, bracket_updated_at: :asc) %>
			<% if !@members.empty? %>
				<table class="table table-striped">
					<tr> 
						<td> Rank </td>
						<td> Screen Name </td>
						<td> Score </td>
						<td> Accuracy </td>
						<td> Round of 16 </td>
						<td> Quater-finals </td>
						<td> Semi-finals </td>
						<td> Total Correct </td>
					</tr>
					<% rank = 1 %>
					<% @members.each do |member| %>
						<% @bracket = Bracket.find_by(user_id: member.user_id) %>
						<tr>
							<td><%= rank %></td>
							<td> <%= member.user_screen_name %> 
								<% if member.user_id == current_user.id %> 
								  <%= link_to " (change)", 'javascript:void(0)', id: "change-screenname" %>
								<% elsif results_visible? %>
									<% if !@bracket.nil? %> 
										<%= link_to " View Bracket", bracket_path(@bracket, other_bracket: true, screen_name: member.user_screen_name ) %>
									<% else %>
								 		(No bracket created)
									<% end %> 
								<% end %>
								</td>
							<td> <%= member.score %></td>
							<td> <%= @bracket.nil? ? '0%' : ((member.score / (positions_defined(@bracket)*2.00))*100).round(0) %>% </td>
							<td> <%=  ((member.full_r16 / 16.00)*100).round(2) %>% / <%= ((member.half_r16 / 16.00)*100).round(2) %>% </td>
							<td> <%= ((member.full_quaterfinals / 8.00)*100).round(2) %>% </td>
							<td> <%= ((member.full_semifinals / 4.00)*100).round(2) %>% </td>
							<td> <%= ((member.full_total / 34.00)*100).round(2) %>% </td>
						</tr>
						<% rank = rank + 1 %>
					<% end %>
				</table>
			<% end %>
		</div>
</div>
		

<div id="leave-group-message" class="warning-message off">
	<br>
	<h4 class="center">Are you sure you want to leave this group?</h4>
	<br>
	<br>
	<%= link_to "Yes", membership_path(@group), method: 'delete', class: 'btn btn-danger btn-message' %>
	<button type="button" class="btn btn-success btn-message " onclick="clearMessage('#leave-group-message')">No</button>
</div>
<div id="delete-group-message" class="warning-message off">
	<br>
	<h4 class="center">Are you sure you want to delete this group?</h4>
	<br>
	<br>
	<%= link_to "Yes", group_path(@group), method: 'delete', class: 'btn btn-danger btn-message' %>
	<button type="button" class="btn btn-success btn-message " onclick="clearMessage('#delete-group-message')">No</button>
</div>
<div id="screenname-form-message" class="warning-message off">
	<h4 class="center">Enter new screen name:</h4>
	<br/>
	<% @this_member = Membership.find_by(user_id: session[:user_id], group_id: @group.id) %>
	<% if !@this_member.nil? %> 
		<%= form_for @this_member do |f| %>
		<%= f.text_field :user_screen_name, class: 'form-input col-md-12' %>
		<br/>
		<br/>
		<br/>
		<button type="button" class="btn btn-primary col-xs-4 col-xs-offset-1" id="cancel-screenname">Cancel</button>
		<%= f.submit  "Save", class: 'btn btn-success col-xs-4 col-xs-offset-2' %>
		<% end %>
	<% end %>
</div>

<script>
		$('#cancel-screenname').click(function (event) {
			clearMessage("#screenname-form-message");
		});
		$('#change-screenname').click(function (event) {
			showMessage("#screenname-form-message");
		});
		$('#button_leave_group').click(function (event) {
			showMessage("#leave-group-message");
		});	
		$('#group_slug').change(function (event) {
			var newGroup = '/groups/'+ $(this).val();
			location.href = newGroup;
		});	

</script>

app/views/groups/_group_table.html.erb
<table class="table">
		<tr>
			<th>Group Name</th>
			<th>Action</th>
			<th>Organizer</th>
			<th>Number of Members</th>
			<th>Group Type</th>
		</tr>
	<% @groups.all.each do |group| %>
		<% if group.is_member?(current_user.id) %>
			<tr>
				<td>
					<%= link_to group.group_name, group_path(group) %>
				</td>
				<td>
					<% if !group.is_private? %>
					   <% if !group.is_organizer?(current_user) %>
							<% if group.is_member?(current_user.id) %>
						   		<%= link_to "Leave Group", group_path(group), :class => "btn btn-danger" %>
							<% else %>
						   		<%= link_to "Join Group", memberships_path(isprivate: false, user_id: current_user, group_id: group.id), :class => "btn btn-success", :method => :post  %>
							<% end %>
						<% end %>
					<% else %>
						<% if !(group.is_organizer?(current_user)) %>
							<%= link_to "Leave Group", group_path(group), :class => "btn btn-danger"  %>
						<% end %>
					<% end %>
				</td>
				<td>
					<% if group.is_organizer?(current_user) %>
						You
					<% else %>
					<%= User.find(group.organizer).first_name%> <%= User.find(group.organizer).last_name%>
					<% end %>
				</td>
				<td><%= Membership.where(group_id: group.id).count() %></td>
				<td><%= group.isprivate ? 'Private' : 'Public' %></td>
			</tr>
		<% end %>
	<% end %>
</table>

app/views/groups/_group_table_public.html.erb
<table class="table">
		<tr>
			<th>Group Name</th>
			<th>Action</th>
			<th>Organizer</th>
			<th>Number of Members</th>
			<th>Group Type</th>
		</tr>
	<% @groups.all.each do |group| %>
		<% if !group.is_member?(current_user.id) %>
			<tr>
				<td>
					<%= link_to group.group_name, group_path(group) %>
				</td>
				<td>
					<% if !group.is_private? %>
					   <% if !group.is_organizer?(current_user) %>
							<% if group.is_member?(current_user.id) %>
						   		<%= link_to "Leave Group", group_path(group), :class => "btn btn-danger" %>
							<% else %>
						   		<%= link_to "Join Group", memberships_path(isprivate: false, group_id: group.id), :class => "btn btn-success", :method => :post %>
							<% end %>
						<% end %>
					<% else %>
						<% if !(group.is_organizer?(current_user)) %>
							<%= link_to "Leave Group", group_path(group), :class => "btn btn-danger"  %>
						<% end %>
					<% end %>
				</td>
				<td>
					<% if group.is_organizer?(current_user) %>
						You
					<% else %>
					<%= User.find(group.organizer).first_name%> <%= User.find(group.organizer).last_name%>
					<% end %>
				</td>
				<td><%= Membership.where(group_id: group.id).count() %></td>
				<td><%= group.isprivate ? 'Private' : 'Public' %></td>
			</tr>
		<% end %>
	<% end %>
</table>

app/views/groups/_group_view_buttons.html.erb
<div class="navbar">
   	<div class="navbar-inner">
       	<div class="container">	
			<nav class="third-navbar" role="navigation">
				<ul class="nav">
				  <li>
				    <%= link_to "Go Back", :back %>
				  </li>
				  <% if (@group.organizer == session[:user_id]) || @group.others_can_invite || !@group.isprivate %>
				  <li>
				    <%= link_to "Invite More Players", inviteothers_path(@group) %>
				  </li>
				  <% end %>
				  <% if @group.organizer == session[:user_id] %>
					  <li>
						<%= link_to "Edit This Group", edit_group_path(@group) %>
					  </li>
					  <li>
					  	<%= link_to "Delete This Group", "#", :onclick => "showMessage('#delete-group-message')" %>
					  </li>
				  <% else %>
				  	  <li>
				      	<%= link_to "Leave This Group", "#", :id => "button_leave_group" %>
				  	  </li>
				<% end %>
				<li>
				    <%= link_to "Create New Group", new_group_path() %>
				  </li>
				  <li>
				    <%= link_to "Join Public Group", groups_path(showpublic: true) %>
				  </li>
				  <li>
				  		<%= link_to "Join Private Group", new_membership_path(isprivate: true) %>
				  </li>
				</ul>
			</nav>
		</div>
	</div>
</div>

app/views/groups/_invite_others_form.html.erb
	<div class="dialog">
		<%= form_tag '/sendinvite' do %>
			<div class='form-instructions'>
				<h4><%= @group.group_name %> Group</h4>
				<h4>Invite more people to this <%= @group.isprivate ? 'private' : 'public' %> group</h4>
				<p> Enter the email addresses of the people that you'd like to invite to the group. You can enter multiple email addresses by separating each one with a comma.</p>
				<br>
			</div>
			<div class='control-group form-row'>
				<label for="emails" class= 'form-label col-lg-2 col-lg-offset-2 col-md-3 col-md-offset-1 col-sm-4 col-xs-11 col-xs-offset-1'>Recipients</label>
				<%= text_field_tag :emails, params[:emails] || '', class: 'form-input col-lg-4 col-md-4 col-sm-5 col-sm-offset-0 col-xs-10 col-xs-offset-1' %>
				<input type='hidden' name='id' value=<%= @group.slug %> />
			</div>
			<div class='control-group form-row form-instructions'>
				<%= submit_tag "Send Invite", class: 'btn-wcb-normal ' %>
			</div>
		<% end %>
	</div>

app/views/groups/edit.html.erb
<%= render 'shared/display_errors', obj: @group %>
<%= render 'group_buttons' %>
<div class='span12 myform'>
	<%= render 'group_new' %> 	
</div>

app/views/groups/index.html.erb
<%= render 'group_buttons' %>
<div class="reportcontainer">
	<%if @groups.empty? %>
		<% if @isprivate %>
			<br>
			<h4 class="center form-instructions">You haven't joined any groups yet. You can join a public group, join a private group if you have the group passcode or create your own group. </h4>
		<% else %> 
			<br>
			<h4 class="center form-instructions">There are no more Public Groups available to join.  </h4>
		<% end %>
	<% else %>
			<div class="well">
				<% if @isprivate %> 
					<%= render 'group_table' %>
				<% else %> 
					<%= render 'group_table_public' %> 
				<% end %>
			</div>
	<% end %>
</div>

app/views/groups/invite_others.html.erb
<%= render 'group_buttons' %>
<div class='span12 myform'>
	<%= render 'invite_others_form' %> 
</div>

app/views/groups/new.html.erb
<%= render 'shared/display_errors', obj: @group %>
<%= render 'group_buttons' %>
<div class='span12 myform'>
	<%= render 'group_new' %> 
</div>

	<script>
		var checkbox = document.getElementById('group_isprivate');
		var passcode = document.getElementById('div_passcode');
		$(document).ready(function(){
     		passcode.style['display'] = 'none';
     		$('.form-input').tooltip({placement: 'left'});
 		 })
		
		checkbox.onchange = function(){
			if(this.checked){
				passcode.style['display'] = 'block';
			} else {
				passcode.style['display'] = 'none';
			}
		};
	</script>

app/views/groups/show.html.erb
	<%= render 'shared/display_errors', obj: @group %>
	
	<%= render 'group_show' %> 
		