config/routes.rb
Rails.application.routes.draw do

  root :to => 'welcome#index'

  resources :brackets, except: :destroy
  resources :users, except: :destroy
  resources :groups
  resources :memberships

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get '/stats', to: 'stats#index'
  get '/wcbadmin', to: 'sessions#admin'
  post '/wcblogin', to: 'sessions#newadmin'
  get '/wcbmgmt', to: 'admin#index'
  get '/attempt', to: 'register_attempts#new'
  post '/attempt', to: 'register_attempts#create'
  get '/updateview', to: 'admin#change_view'
  get '/usersearch', to: 'admin#user_search'
  get '/admininfo', to: 'admin#admin_info'
  post '/teamupdate/:id', to: 'admin#team_update', as: 'teamupdate'
  get '/teamindex', to: 'admin#team_index' 
  get '/teamedit/:id', to: 'admin#team_edit', as: 'teamedit'
  get '/rules', to: 'rules#index', as:'rules'
  get '/groupinvite/:id', to: 'groups#invite_others', as: 'inviteothers'
  post '/sendinvite', to: 'groups#send_invite', as: 'sendinvite'
  get '/recoverpassword', to: 'users#recover_password', as: 'recoverpassword'
  post '/recover_password_email', to: 'users#recover_password_email', as: 'recover_password_email'
  get '/password_modify', to: 'users#password_modify', as: 'password_modify'
  get '/registerattempts', to: 'admin#register_attempts'
  get '/howdoesitwork', to: 'welcome#how_does_it_work'
  get '/unsupportedbrowser', to: 'welcome#unsupported_browser'
  get '*path', to: 'welcome#index'
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	
	def index
		if logged_in?
			if is_admin? && admin_view?
				redirect_to admininfo_path
			else
				redirect_to bracket_path(current_user.slug)
			end
		end
	end

	def how_does_it_work

	end

	def unsupported_browser

	end

end

app/views/welcome/how_does_it_work.html.erb
<div class="display-container">
	<br>
	<h3>How does it work</h3>
	<br>
	<h5>1. You create a bracket to predict the outcome of the World Cup. The bracket starts on the Round of 16.</h5>
	<div class="how-image" id="bracket-empty"></div>
	<h5>2. The game will update your score as the World Cup progresses.</h5>
	<div class="how-image" id="bracket-full"></div>
	<h5>3. You can create private groups to compete with friends or join public groups. You can only create one bracket per account. This bracket will be used to compete in all your groups.</h5>
	<div class="how-image" id="group-full"></div>
	<h5>Ready to Play? <%= link_to 'Register Here', attempt_path %>
</div>

<script>
 	  $('body').css({"min-width": "0px"});
</script>

app/views/welcome/index.html.erb
<link href="http://fonts.googleapis.com/css?family=Luckiest+Guy" rel="stylesheet" type="text/css">
<div class='login-background'>
	<br>
	<br>
	<br>
	<br>
    <h1 id="thirtytwo" class="title line1" style="position:relative; opacity:0; display:none">32</h1>
    <h1 id="teams" class="title line1" style="position:relative; opacity:0; display:none">Teams</h1>
    <h1 id="sixtyfour" class="title line2" style="position:relative; opacity:0; display:none">64</h1>
    <h1 id="games" class="title line2" style="position:relative; opacity:0; display:none">Games</h1>
    <h1 id="sevenhundred" class="title line3" style="position:relative; opacity:0; display:none">736</h1>
    <h1 id="players" class="title line3" style="position:relative; opacity:0; display:none">Players</h1>
    <h1 id="one" class="title line4" style="position:relative; display:none">One</h1>
    <br>
    <h1 id="single" class="title line4" style="position:relative; display:none">Single</h1>
    <br>
    <h1 id="dream" class="title line4" style="position:relative; display:none">Dream</h1>
</div>

 <script>
 	  $('body').css({"min-width": "0px"});
      $(document).ready(function(){
        (new TimelineLite())
        .to( $('#thirtytwo'), 0.1, {css:{display:'block'}})
        .to( $('#teams'), 0.1, {css:{display:'block'}})
        .to( $('#thirtytwo'), 0.6, {css:{opacity:1}})
        .to( $('#thirtytwo'), 1, {scaleX:3, scaleY:3})
        .to( $('#teams'), 0.1, {scaleX:2, scaleY:2})
        .to( $('#teams'), 1, {css:{opacity:1}})
        .to( $('.line1'), 1, {css:{opacity:0}})
        .to( $('#thirtytwo'), .1, {css:{display:'none'}})
        .to( $('#teams'), .1, {css:{display:'none'}})
        .to( $('#sixtyfour'), 0.1, {css:{display:'block'}})
        .to( $('#games'), 0.1, {css:{display:'block'}})
        .to( $('#sixtyfour'), 0.6, {css:{opacity:1}})
        .to( $('#sixtyfour'), 1, {scaleX:3, scaleY:3})
        .to( $('#games'), 0.1, {scaleX:2, scaleY:2})
        .to( $('#games'), 1, {css:{opacity:1}})
        .to( $('.line2'), 1, {css:{opacity:0}})
        .to( $('#sixtyfour'), .1, {css:{display:'none'}})
        .to( $('#games'), .1, {css:{display:'none'}})
        .to( $('#sevenhundred'), 0.1, {css:{display:'block'}})
        .to( $('#players'), 0.1, {css:{display:'block'}})
        .to( $('#sevenhundred'), 1, {css:{opacity:1}})
        .to( $('#sevenhundred'), 0.4, {scaleX:3, scaleY:3})
        .to( $('#players'), 0.1, {scaleX:2, scaleY:2})
        .to( $('#players'), 1, {css:{opacity:1}})
        .to( $('.line3'), 1, {css:{opacity:0}})
        .to( $('#sevenhundred'), .1, {css:{display:'none'}})
        .to( $('#players'), .1, {css:{display:'none'}})
        .to( $('#one'), 0.1, {css:{display:'block'}})
        .to( $('#single'), 0.1, {css:{display:'block'}})
        .to( $('#dream'), 0.1, {css:{display:'block'}})
        .from( $('#one'), .6, {delay:0.2, css:{right:'1000px'}, ease:Power4.easeOut})
        .to( $('#one'), 0.4, {scaleX:3, scaleY:3})
        .from( $('#single'), .6, {delay:0.2, css:{left:'1000px'}, ease:Power4.easeOut})
        .to( $('#single'), 0.4, {scaleX:3, scaleY:3})
        .from( $('#dream'), 0.6, {css:{opacity:0}})
        .to( $('#dream'), 0.4, {scaleX:3, scaleY:3})
      });
</script>

app/views/welcome/unsupported_browser.html.erb
<div class="display-container">
	<br>
	<h5>Brazil 2014 World Cup Bracket Game. Create groups, keep track of your score and play with friends!<h5>
	<br>
	<h3>Thank you for accessing theworldcupbracket.com</h3>
	<br>
	<h5>Unfortunately, your broswer is not supported by this application.</h5>
	<h5>Please try accessing the site using one of the following browsers:</h5>
	<h5>1. Google Chrome version 28 or above (recommended)</h5>
	<h5>2. Firefox version 19 or above</h5>
	<h5>3. Safari version 6.0.2 or above</h5>
	<h5>4. Internet Explorer 10.0 or above</h5>
	<br>
	<h5>We apologize for the inconvenience.</h5>
</div>

<script>
 	  $('body').css({"min-width": "0px"});
</script>